### ISSUE TITLE
I can't update ACF

### ISSUE THREAD

**Issue by ioneill** [pivvenit/acf-composer-bridge#11]
`  - Installing advanced-custom-fields/advanced-custom-fields-pro (5.9.4): Downloading (failed)

  [Composer\Downloader\TransportException]
  The "https://connect.advancedcustomfields.com/v2/plugins/download?p=pro&t=5.9.4" file could not be downloaded (HTTP/1.1 404 Not Found)
`
ACF_PRO_KEY is in my .env file, and is correct. Is this a known issue?

**Comment by Qrious** [comment]
Hi,

I'm unable to reproduce this issue locally. Can you please provide me with the following information:

1. Which composer repository do you use?
2. Which is your composer version? You can obtain it by running `composer --version`.

3. Does the below  `composer.json` example work for you with the following command: `composer install --no-cache -vvv`
Can you please provide me with the relevant lines i've posted below (mind to remove your key)
```json
{
  "name": "example/test",
  "repositories": [
    {
      "type": "composer",
      "url": "https://pivvenit.github.io/acf-composer-bridge/composer/v3/wordpress-muplugin/"
    }
  ],
  "require": {
    "advanced-custom-fields/advanced-custom-fields-pro": "^5.9.4"
  }
}
```

```
[...]  // Lots of lines before this
> pre-file-download: PivvenIT\Composer\Installers\ACFPro\ACFProInstallerPlugin->onPreFileDownload
  - Downloading advanced-custom-fields/advanced-custom-fields-pro (5.9.3)
Downloading https://connect.advancedcustomfields.com/v2/plugins/download?p=pro&t=5.9.3&k={KEY HERE}
  - Installing composer/installers (v1.9.0): Extracting archive
Executing command (CWD): rmdir /S /Q "{PATH}\vendor\composer\installers"
Executing command (CWD): rmdir /S /Q "{PATH}\vendor\composer\1c21e311"
Loading plugin Composer\Installers\Plugin
  - Installing advanced-custom-fields/advanced-custom-fields-pro (5.9.3): Extracting archive
Executing command (CWD): rmdir /S /Q "{PATH}\wp-content\mu-plugins\advanced-custom-fields-pro"
Executing command (CWD): rmdir /S /Q "{PATH}\vendor\composer\6adea1ba"
Executing command (CWD): rmdir /S /Q "{PATH}\vendor\advanced-custom-fields\advanced-custom-fields-pro"
```

**Comment by Sandy-Garrido** [comment]
I'm also getting this issue! @Qrious, it was fine before Dec when I last checked it
