### ISSUE TITLE
The packages.json file doesn't have the lates version

### ISSUE THREAD

**Issue by andreicnegrea** [pivvenit/acf-composer-bridge#15]
Hi,

The [packages.json](https://pivvenit.github.io/acf-composer-bridge/composer/v3/packages.json) files don't contain version 5.10.1.

How often is the file updated? Thanks!

**Comment by Qrious** [comment]
Hi,

The repo is updated every two hours, however the ACF data contained a non fully formatted semver for the first time (5.10 vs 5.10.0), which caused the build script to fail. This has been fixed.
