### ISSUE TITLE
404 - Broken

### ISSUE THREAD

**Issue by nielsvr** [pivvenit/acf-composer-bridge#18]
The components seem to be broken. URLs throw a 404. Composer fails.

https://pivvenit.github.io/acf-composer-bridge/composer/v3/library/

**Comment by andrewmumblebee** [comment]
Same here, getting 404 when our pipeline trys to install acf-pro using this

**Comment by Qrious** [comment]
Hmm, that is strange, it works on my machine™.

Could please create a new folder with the following `composer.json` and run `composer install --no-cache`? Does this work correctly?

```json
{
  "name": "example/test",
  "repositories": [
    {
      "type": "composer",
      "url": "https://pivvenit.github.io/acf-composer-bridge/composer/v3/library/"
    }
  ],
  "require": {
    "advanced-custom-fields/advanced-custom-fields-pro": "5.12"
  },
  "config": {
    "allow-plugins": {
      "pivvenit/acf-pro-installer": true,
      "composer/installers": true
    }
  }
}
```

**Comment by swannknani** [comment]
Same here :(

**Comment by ianleckey** [comment]
Same here:

`  [Composer\Downloader\TransportException]                                                                                                  
  The "https://connect.advancedcustomfields.com/v2/plugins/download?p=pro&t=5.12.2" file could not be downloaded (HTTP/1.1 404 Not Found):  
  {"code":"api_error","message":"Sorry, something went wrong.","data":{"status":404}}      `

**Comment by mrmadhat** [comment]
Having the same issue, when I run `composer update --no-cache` locally the download still works for me but when I try to deploy (using deployhq) I'm getting the same errors others have mentioned.

**Comment by ianleckey** [comment]
> Having the same issue, when I run `composer update --no-cache` locally the download still works for me but when I try to deploy (using deployhq) I'm getting the same errors others have mentioned.

I was also using deployhq. Have a read through the build log and you'll see stuff like:
> contains a Composer plugin which is blocked by your allow-plugins config

Then add all of the references plugins to allow-plugins in your composer.json:
`  "config": {
    "allow-plugins": {
      "pivvenit/acf-pro-installer": true,
      "composer/installers": true
    }
  }`

**Comment by mrmadhat** [comment]
Thanks @ianleckey everything's working again now 😄 It looks like my local version of composer is using 2.1.5 whereas deployhq is using >=2.2 so `allow-plugins` is now required.

>As of Composer 2.2. 0, the allow-plugins option adds a layer of security allowing you to restrict which Composer plugins are able to execute code during a Composer run. When a new plugin is first activated, which is not yet listed in the config option, Composer will print a warning.

https://getcomposer.org/doc/06-config.md#allow-plugins
