### ISSUE TITLE
Any chance of delaying shut down by a few days?

### ISSUE THREAD

**Issue by paulshryock** [pivvenit/acf-composer-bridge#20]
Hello,

I see the notice about this repo shutting down tomorrow, 2023/06/01. For the last month, I've been talking with my employer's IT department trying to track down who has our ACF Pro account credentials so I can login and generate the `auth.json` file to switch over to installing ACF Pro via Composer natively.

As of today, we haven't yet tracked down those credentials, so I'm worried about what will happen on our next production deployment starting tomorrow. If I'm reading the notice in the Readme correctly, it looks like our builds will fail during `composer install`, and we'll be blocked from releasing to production until we locate those credentials (or check the ACF Pro source code into version control).

Am I understanding correctly that the service will completely stop working on June 1st? If so, is there any chance of waiting a few more days to shut it down? If not, I understand, but wanted to see if this was an option.

Thanks!

**Comment by Qrious** [comment]
Hello,

Apologies for the late reply.
The repository will remain active till the 1st of July for now, since we are still having 1 legacy project depending on it. It's shutdown has been delayed by one month, so till that time it will be online. Afterwards it will completely stop working.

**Comment by paulshryock** [comment]
Thanks @Qrious! We are actively working on migrating off this, and I really appreciate the extra time.
