### ISSUE TITLE
Latest update deletes old versions

### ISSUE THREAD

**Issue by schliflo** [pivvenit/acf-composer-bridge#3]
The latest update on the `gh-pages` branch seems to delete all old versions: https://github.com/pivvenit/acf-composer-bridge/commit/6601c5b6eab5f3731f6b0e8873be029b097229b4

I haven't actually tested installing older versions but, it's probably broken if they are missing.

**Comment by Qrious** [comment]
Thanks for notyfing, i'll fix it now (and add some monitoring).
